### PR TITLE
C++ constructors/destructors

### PR DESCRIPTION
**Pull request by msbit**
Continued work on embracing the ++ in C++.

I've broken it down into smallish commits to take a look at, much of it is relatively mechanical refactoring of free functions into constructors etc. There would be ongoing work into the ergonomics of cleaning up uses of `this->` in constructors etc but this is a start.

As usual, if you want to take what you've learned from these commits and reimplement yourself to consolidate that, feel free :)

### CODE REVIEW

**Comment by stewartmatheson** [comment]
Hey Tom,

This is awesome! I'm wondering if its worth going all the way and converting structs to classes? I think I will be doing that regardless when I introduce the state machine to transition between the different scenes of the game.

**Comment by msbit** [comment]
@stewartmatheson from what I've read around the place, the one difference is the default visibility of members, ie for a `struct`, the default visibility is `public`, and for a `class`, `private`.

[This](https://www.fluentcpp.com/2017/06/13/the-real-difference-between-struct-class/) makes a point regarding the intention communicated through using either; seeing `struct` you'll think "a bunch of data", seeing `class` you'll think "some data and some actions". Not that I've written much C++ in anger, but I tend to start with `struct`s (to avoid unnecessary `public` noise) then think about it later.

Based on that, I'd say `Editor` would suit being a `class`, with `DrawEditor`, and `UpdateEditor` moved into member methods, as would `Room` (with `WriteRoomToFile` and `DrawRoom` moved to member methods), whereas `TileMap` and `Tile` could remain `struct`s.

**Comment by stewartmatheson** [comment]
Yeah is where I saw things going. PR's very welcome. I'm going to create the player now and I will use a class for the first time.

**Comment by msbit** [comment]
@stewartmatheson sounds good. I've opened #6 for that.

**Pull request merged**
