### PR TITLE
Replace explicit iterator loop with range-based for loop

### PR DESCRIPTION
**Pull request by msbit**

### CODE REVIEW

**Comment by msbit** [comment]
Another cute three word aphorism from one of the revered C++ boffins:

  [No Raw Loops](https://youtu.be/W2tWOdzgXHA?t=131)

That talk in general is very good, and worth a watch, but what I've taken from that part is to lean on the STL algorithms, if they apply for the situation, and that this can make the code less noisy.

In these cases so far, using `std::find_if` makes it clear that we're finding one thing, based on some encapsulable predicate, and it removes the boilerplate of the loop proper.

**Comment by msbit** [comment]
Oh and I suspect a bunch of these PRs will trample on each other, so if you want, merge the ones that will go cleanly, and ping me to rebase the ones that won't.

**Comment by stewartmatheson** [comment]
Interesting. I saw Jason Turner talk about this as well in an episode. I think it was the one where he refactored doom to c++ but I can't remember TBH. Long video but worth spending a few mins scrubbing though 

https://www.youtube.com/watch?v=d1BwjUlwYeg

**Comment by msbit** [comment]
Big fan of Turner, I'll take a look.

Also realised these comments should have been on https://github.com/stewartmatheson/projectx/pull/25 :P

**Pull request merged**
